title: My AI Journey
description: A running record of my experience using AI / LLM
baseurl: ""        # leave blank when hosting at the repo root
url: "https://sccardais.github.io"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme